# /var/www/html/vayuadmin/docker-compose.yml (yml file inside project root dir )

# ./docker-compose.yml

# /var/www/html/vayuadmin $ docker-compose up
# http://localhost:8080/vayuadmin

version: '2'
services:
  app:
    build:
      context: . # path of directory containing a Dockerfile, or a url to a git repository.
      dockerfile: ./docker/Dockerfile
    image: vayuadmin-docker-img
    ports:
      - 8080:80
    volumes: 
      - .:/var/www/html
#      - .:/var/log/apache2
#    links:
#      - mysql
#      - redis
#    environment:
#      DB_HOST: mysql
#      DB_DATABASE: laravel_docker
#      DB_USERNAME: app
#      DB_PASSWORD: password
#      REDIS_HOST: redis
#      SESSION_DRIVER: redis
#      CACHE_DRIVER: redis
#  mysql:
#    image: mysql:5.7
#    ports:
#      - 13306:3306
#    environment:
#      MYSQL_DATABASE: laravel_docker
#      MYSQL_USER: app
#      MYSQL_PASSWORD: password
#      MYSQL_ROOT_PASSWORD: password
#  redis:
#    image: redis:4.0-alpine
#    ports:
#      - 16379:6379
